### PR TITLE
status endpoint: more eloquent JSON key for the total number of users

### PR DESCRIPTION
**Pull request by marfox**

### CODE REVIEW

**Comment by tomayac** [comment]
Thanks for the pull request. Is a fix on the consuming side required to make this work?

**Comment by marfox** [comment]
Hey @tomayac, I am aware of just one endpoint that is consuming the status response:
https://tools.wmflabs.org/wikidata-primary-sources/status.html
but it is not taking into account the key I have updated, so it should not be an issue.

**Comment by tomayac** [comment]
Alright, merged. Thanks :-) Sorry for the short notice, but could an admin deploy this new version, too, now that the last deploy happened literally only minutes ago?

**Comment by marfox** [comment]
I'm working right now on #98, so I suggest to wait for the fix before redeploying the backend.

**Pull request merged**
